#!/usr/bin/env bash
set -euo pipefail

export MF_VERSION="${MF_VERSION:-1}"
export MF_ROOT="${MF_ROOT:-$(pwd)/.makefiles}"

if [[ ! -d "$MF_ROOT/lib/core" ]]; then
    echo "downloading makefiles.dev core library"

    tmpdir="$(mktemp -d)"
    trap "rm -rf '$tmpdir'" EXIT

    curl \
        --fail \
        --silent \
        --show-error \
        --location \
        --create-dirs \
        --output "$tmpdir/archive.zip" \
        "https://github.com/make-files/lib-core/archive/v$MF_VERSION.zip?nonce=$(uuidgen)"

    unzip -q "$tmpdir/archive.zip" -d "$tmpdir"
    mkdir -p "$MF_ROOT/lib"
    mv "$tmpdir/lib-core-$MF_VERSION" "$MF_ROOT/lib/core"
    "$MF_ROOT/lib/core/bin/install-hook"
fi

"$MF_ROOT/bin/mf" build "$1"
