#!/usr/bin/env bash
set -euo pipefail

MF_VERSION=1

if [[ ! -d ".makefiles/lib/core" ]]; then
    echo "downloading makefiles.dev core"

    tmpdir="$(mktemp -d)"
    trap "rm -rf '$tmpdir'" EXIT

    curl \
        --fail \
        --silent \
        --show-error \
        --location \
        --create-dirs \
        --output "$tmpdir/archive.zip" \
        "https://github.com/make-files/lib-core/archive/v$MF_VERSION.zip?nonce=$(uuidgen)"

    unzip -q "$tmpdir/archive.zip" -d "$tmpdir"
    mkdir -p ".makefiles/lib"
    mv "$tmpdir/lib-core-v$MF_VERSION" ".makefiles/lib/core"

    .makefiles/lib/core/mf install core
fi

.makefiles/lib/core/mf build "$1"
