#!/usr/bin/env bash
set -euo pipefail

# MF_PROJECT_ROOT must always be defined.
export MF_PROJECT_ROOT="${MF_PROJECT_ROOT:-$(pwd)}"

# Check if we've already got the makefiles.
if [[ ! -d ".makefiles" ]]; then
    if [[ $MAKEFLAGS =~ (^|[^[:alnum:]_])j([^[:alnum:]_]|$) ]]; then
        echo 'Run "make makefiles" before running make -j'
        exit 1
    fi

    tmpdir="$(mktemp -d)"
    trap "rm -rf '$tmpdir'" EXIT

    # Download the makefiles.
    curl \
        --fail \
        --silent \
        --show-error \
        --location \
        --create-dirs \
        --output "$tmpdir/archive.zip" \
        "https://github.com/make-files/makefiles/archive/v1.zip?nonce=$(uuidgen)"

    # Unpack the archive from the subdirectory that GitHub adds into the .makefiles directory.
    unzip -q "$tmpdir/archive.zip" -d "$tmpdir"
    mv "$tmpdir/makefiles-1" ".makefiles"

    # Run the install command for the core library. Because it is already in the
    # correct location this will simply run the install hooks.
    .makefiles/lib/core/bin/install-lib core
fi

# Finally, invoke the build-resource command to produce the actual resource that
# was requested.
.makefiles/lib/core/bin/build-resource "$1"
